name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.60.231.71 >> ~/.ssh/known_hosts
          
          ssh -o StrictHostKeyChecking=no ubuntu@13.60.231.71 -i ~/.ssh/id_rsa << EOF
          cd fastapi-book-project || exit 1  # Ensure the folder exists
          git pull origin main  # Pull latest code

          # Ensure Docker daemon is running
          sudo systemctl start docker

          # Stop and remove old container if it exists
          sudo docker stop fastapi_container || true
          sudo docker rm fastapi_container || true

          # Remove old Docker image
          sudo docker rmi fastapi_image || true

          # Build and run new container
          sudo docker build -t fastapi_image .  # Build new image
          sudo docker run -d --name fastapi_container -p 8000:8000 fastapi_image  # Run container

          # Cleanup unused images
          sudo docker system prune -f  
          EOF
